# typed: false
# frozen_string_literal: true

# This file is generated by scripts/update-tap.sh. DO NOT EDIT.
class Ewch < Formula
  desc "Opinionated Git repository bootstrapper with Grove worktrees"
  homepage "https://github.com/planesailingio/ewch"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/planesailingio/ewch/releases/download/v0.1.0/ewch_0.1.0_x86_64-apple-darwin.tar.gz"
      sha256 "8269b735623bf490ac1237135d9ea24dc5446ea8d69c1746ff97fc304b5a89d8"

      def install
        bin.install "bin/ewch"
      end
    end
    on_arm do
      url "https://github.com/planesailingio/ewch/releases/download/v0.1.0/ewch_0.1.0_aarch64-apple-darwin.tar.gz"
      sha256 "e6430c9ed4cce3e8d24d392d68eab10161ef7a827748526ec315d39025df360a"

      def install
        bin.install "bin/ewch"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planesailingio/ewch/releases/download/v0.1.0/ewch_0.1.0_x86_64-unknown-linux-gnu.tar.gz"
        sha256 "a84409508f579c41128e85101ff5039219f21ed9e8cd30738d5bbea632473d77"

        def install
          bin.install "bin/ewch"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planesailingio/ewch/releases/download/v0.1.0/ewch_0.1.0_aarch64-unknown-linux-gnu.tar.gz"
        sha256 "ad3f428ac0ba155df5aef700a531b4caf545a252288eb110c119172de241248f"

        def install
          bin.install "bin/ewch"
        end
      end
    end
  end

  test do
    assert_match "ewch", shell_output("#{bin}/ewch version")
  end
end
