# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotfhub < Formula
  desc ""
  homepage ""
  version "0.0.12"

  on_macos do
    on_intel do
      url "https://github.com/planesailingio/gotfhub/releases/download/0.0.12/gotfhub_0.0.12_darwin_amd64.tar.gz"
      sha256 "79e12b36e03748553818c4b996799d910ae0352436eab9f1b6338ed575f41358"

      def install
        bin.install "bin/0.0.12/darwin/amd64/gotfhub"
      end
    end
    on_arm do
      url "https://github.com/planesailingio/gotfhub/releases/download/0.0.12/gotfhub_0.0.12_darwin_arm64.tar.gz"
      sha256 "a8da722b3f5309fef1f4153fc7f44383e2da67bdd0571e249da881ac535266cf"

      def install
        bin.install "bin/0.0.12/darwin/arm64/gotfhub"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planesailingio/gotfhub/releases/download/0.0.12/gotfhub_0.0.12_linux_amd64.tar.gz"
        sha256 "23e7ee9ceed951105541f6f474f3d5666a18ae10e595b740e7589b200a3b2db5"

        def install
          bin.install "bin/0.0.12/linux/amd64/gotfhub"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planesailingio/gotfhub/releases/download/0.0.12/gotfhub_0.0.12_linux_arm64.tar.gz"
        sha256 "dc43af4e06809470f64fe8bd940611b4856c787a2584395bd5486e71052662ef"

        def install
          bin.install "bin/0.0.12/linux/arm64/gotfhub"
        end
      end
    end
  end
end
