# typed: false
# frozen_string_literal: true

# This file is generated by scripts/update-tap.sh. DO NOT EDIT.
class Twig < Formula
  desc "Opinionated Git repository bootstrapper with Grove worktrees"
  homepage "https://github.com/planesailingio/twig"
  version "0.8.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/planesailingio/twig/releases/download/v0.8.2/twig_0.8.2_x86_64-apple-darwin.tar.gz"
      sha256 "6230f4f9adec39398027a662268715079194d65a94c0a78e0aec758fbf081752"

      def install
        bin.install "bin/twig"
      end
    end
    on_arm do
      url "https://github.com/planesailingio/twig/releases/download/v0.8.2/twig_0.8.2_aarch64-apple-darwin.tar.gz"
      sha256 "4e963e7461c258b7ea758884377ca1335338f4e86b6b6680a30bf1224516bacc"

      def install
        bin.install "bin/twig"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planesailingio/twig/releases/download/v0.8.2/twig_0.8.2_x86_64-unknown-linux-gnu.tar.gz"
        sha256 "5a769410304af37fa190869ad33fe1edd06fa6638d353ffe3204c52478fd0019"

        def install
          bin.install "bin/twig"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planesailingio/twig/releases/download/v0.8.2/twig_0.8.2_aarch64-unknown-linux-gnu.tar.gz"
        sha256 "69f14dd191f11707ef6313f665b77e06fce889de6c3b097a4359df53d7835a1d"

        def install
          bin.install "bin/twig"
        end
      end
    end
  end

  test do
    assert_match "twig", shell_output("#{bin}/twig version")
  end
end
