# typed: false
# frozen_string_literal: true

# This file is generated by scripts/update-tap.sh. DO NOT EDIT.
class Twig < Formula
  desc "Opinionated Git repository bootstrapper with Grove worktrees"
  homepage "https://github.com/planesailingio/twig"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/planesailingio/twig/releases/download/v0.2.0/twig_0.2.0_x86_64-apple-darwin.tar.gz"
      sha256 "15dbfd46cfb05f3b8b601ce90433ac6c301d5f57fc8c3317d0b853730a40a974"

      def install
        bin.install "bin/twig"
      end
    end
    on_arm do
      url "https://github.com/planesailingio/twig/releases/download/v0.2.0/twig_0.2.0_aarch64-apple-darwin.tar.gz"
      sha256 "c3770937e1b038e49a137ec1f1e06ef532da7aeefbb81a5bfc6583fd2b1183b1"

      def install
        bin.install "bin/twig"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planesailingio/twig/releases/download/v0.2.0/twig_0.2.0_x86_64-unknown-linux-gnu.tar.gz"
        sha256 "98a7dfd31a75b0fe678330672cca1d52422ad38c929f999ec8904b753d0b59cb"

        def install
          bin.install "bin/twig"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planesailingio/twig/releases/download/v0.2.0/twig_0.2.0_aarch64-unknown-linux-gnu.tar.gz"
        sha256 "43db76281ff1c0bdda0bcde8dc6c2369adafed4eed9a7219cb9b46320173448a"

        def install
          bin.install "bin/twig"
        end
      end
    end
  end

  test do
    assert_match "twig", shell_output("#{bin}/twig version")
  end
end
