# typed: false
# frozen_string_literal: true

# This file is generated by scripts/update-tap.sh. DO NOT EDIT.
class Twig < Formula
  desc "Opinionated Git repository bootstrapper with Grove worktrees"
  homepage "https://github.com/planesailingio/twig"
  version "0.8.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/planesailingio/twig/releases/download/v0.8.1/twig_0.8.1_x86_64-apple-darwin.tar.gz"
      sha256 "26aba28b8d903cc226d533a97b0e170ba21360e8078764cbc0e60f4eeb058261"

      def install
        bin.install "bin/twig"
      end
    end
    on_arm do
      url "https://github.com/planesailingio/twig/releases/download/v0.8.1/twig_0.8.1_aarch64-apple-darwin.tar.gz"
      sha256 "82aeabd600b09875f5b96336c0f80908f086b1959202526fd821ff544095ce01"

      def install
        bin.install "bin/twig"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planesailingio/twig/releases/download/v0.8.1/twig_0.8.1_x86_64-unknown-linux-gnu.tar.gz"
        sha256 "d7d5096d945e9ff51cd4dd66d4251844cb5fe457b8eb9b5598484979d33439bc"

        def install
          bin.install "bin/twig"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planesailingio/twig/releases/download/v0.8.1/twig_0.8.1_aarch64-unknown-linux-gnu.tar.gz"
        sha256 "11ae24be40d500e5ae418b8bbbf8d3b5ecfdea4f53957df5b89443d1b0f913ee"

        def install
          bin.install "bin/twig"
        end
      end
    end
  end

  test do
    assert_match "twig", shell_output("#{bin}/twig version")
  end
end
