# typed: false
# frozen_string_literal: true

# This file is generated by scripts/update-tap.sh in planesailingio/bosun. DO NOT EDIT.
class Bosun < Formula
  desc "Machine and shell bootstrap: dotfiles, brew bundles and hooks"
  homepage "https://github.com/planesailingio/bosun"
  version "0.1.0"
  license "MIT"

  # git is the only hard requirement, and every machine with a dotfiles repo
  # already has it. zsh and brew itself are reported by `bosun doctor`.

  on_macos do
    on_intel do
      url "https://github.com/planesailingio/bosun/releases/download/v0.1.0/bosun_0.1.0_x86_64-apple-darwin.tar.gz"
      sha256 "da629863dd8009fdbad27614b565227d59d4cc19a1608953a9fd0f0ab2711bd0"
    end
    on_arm do
      url "https://github.com/planesailingio/bosun/releases/download/v0.1.0/bosun_0.1.0_aarch64-apple-darwin.tar.gz"
      sha256 "4ac3878d2995b905389baa1e7dbfe818222fe47110fc050e79d12099edfe008b"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planesailingio/bosun/releases/download/v0.1.0/bosun_0.1.0_x86_64-unknown-linux-gnu.tar.gz"
        sha256 "a807b1172d9d730819c40e68c1aae8f040faee0c54587d5d43718885398a4ed0"
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planesailingio/bosun/releases/download/v0.1.0/bosun_0.1.0_aarch64-unknown-linux-gnu.tar.gz"
        sha256 "65a2da0f4b6bc73ec5b2c7e7adee55236d4617f52b3b25699edac226fb9e10d5"
      end
    end
  end

  def install
    bin.install "bin/bosun"
    bash_completion.install "completions/bosun.bash" => "bosun"
    zsh_completion.install "completions/_bosun"
    fish_completion.install "completions/bosun.fish"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bosun --version")
    # doctor exits non-zero in the sandbox because no repo is cloned there, but
    # the report must still name the git check, which proves it ran.
    assert_match "git", shell_output("#{bin}/bosun doctor 2>&1 || true")
  end
end
