# typed: false
# frozen_string_literal: true

# This file is generated by scripts/update-tap.sh in planesailingio/bosun. DO NOT EDIT.
class Bosun < Formula
  desc "Machine and shell bootstrap: dotfiles, brew bundles and hooks"
  homepage "https://github.com/planesailingio/bosun"
  version "0.2.0"
  license "MIT"

  # git is the only hard requirement, and every machine with a dotfiles repo
  # already has it. zsh and brew itself are reported by `bosun doctor`.

  on_macos do
    on_intel do
      url "https://github.com/planesailingio/bosun/releases/download/v0.2.0/bosun_0.2.0_x86_64-apple-darwin.tar.gz"
      sha256 "ea5bc5e0fcd69bd92554d10023489934a1a4928e08a2c11c0b33e0c18a6c2d10"
    end
    on_arm do
      url "https://github.com/planesailingio/bosun/releases/download/v0.2.0/bosun_0.2.0_aarch64-apple-darwin.tar.gz"
      sha256 "5592f7b3475ad2c58d124d854ccdd5afb802c78c7a522239d3ebe5a86b0af41c"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planesailingio/bosun/releases/download/v0.2.0/bosun_0.2.0_x86_64-unknown-linux-gnu.tar.gz"
        sha256 "8e6604651b7d313776fad1f8bce834a62693aae92765852fd60d1741392571e2"
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planesailingio/bosun/releases/download/v0.2.0/bosun_0.2.0_aarch64-unknown-linux-gnu.tar.gz"
        sha256 "8d11f830eac1aeaa2bb2acdc3b95611d653200c920dd037db836bb2382e11d4b"
      end
    end
  end

  def install
    bin.install "bin/bosun"
    bash_completion.install "completions/bosun.bash" => "bosun"
    zsh_completion.install "completions/_bosun"
    fish_completion.install "completions/bosun.fish"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bosun --version")
    # doctor exits non-zero in the sandbox because no repo is cloned there, but
    # the report must still name the git check, which proves it ran.
    assert_match "git", shell_output("#{bin}/bosun doctor 2>&1 || true")
  end
end
