# typed: false
# frozen_string_literal: true

# Generated by the release workflow in planesailingio/gannet — do not edit by hand.
class Gannet < Formula
  desc "Lightweight package manager for GitHub release binaries"
  homepage "https://github.com/planesailingio/gannet"
  version "0.8.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/planesailingio/gannet/releases/download/v0.8.1/gannet-v0.8.1-aarch64-apple-darwin.tar.gz"
      sha256 "ed8a86be0cb1db65c84813847e494063858ced14aa3d4a2a349fcac1f722d960"
    end
    on_intel do
      url "https://github.com/planesailingio/gannet/releases/download/v0.8.1/gannet-v0.8.1-x86_64-apple-darwin.tar.gz"
      sha256 "17309538d3de2eecb8ff8fe21b842ce8aa245658cea12e580dd33cc11e216dc2"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/planesailingio/gannet/releases/download/v0.8.1/gannet-v0.8.1-aarch64-unknown-linux-musl.tar.gz"
      sha256 "1326fd4928f9e8fae80d8d2cc8c7d889655bb25be044ff68b415bc4392fb3715"
    end
    on_intel do
      url "https://github.com/planesailingio/gannet/releases/download/v0.8.1/gannet-v0.8.1-x86_64-unknown-linux-musl.tar.gz"
      sha256 "658cf809b7a928c8d3ce00cde3ac3b434a9db4abfded961f60e39433fec05c9c"
    end
  end

  def install
    bin.install "gannet"
    bash_completion.install "completions/gannet.bash" => "gannet"
    zsh_completion.install "completions/_gannet"
    fish_completion.install "completions/gannet.fish"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gannet --version")
  end
end
