# typed: false
# frozen_string_literal: true

# Generated by the release workflow in planesailingio/gannet — do not edit by hand.
class Gannet < Formula
  desc "Lightweight package manager for GitHub release binaries"
  homepage "https://github.com/planesailingio/gannet"
  version "0.6.5"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/planesailingio/gannet/releases/download/v0.6.5/gannet-v0.6.5-aarch64-apple-darwin.tar.gz"
      sha256 "5e1abbbf437cb314e990fd10ea230914720bcfdeef2a52a0d71e01e90f8213ba"
    end
    on_intel do
      url "https://github.com/planesailingio/gannet/releases/download/v0.6.5/gannet-v0.6.5-x86_64-apple-darwin.tar.gz"
      sha256 "e96bdd2aee91c631bff11d9e406165a1dfb071388096b2b34813ba4795df5f79"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/planesailingio/gannet/releases/download/v0.6.5/gannet-v0.6.5-aarch64-unknown-linux-musl.tar.gz"
      sha256 "7dea7a4fe8d0eedabcf4e5d63138297e8969673f641945c7ffc40df475d42b4b"
    end
    on_intel do
      url "https://github.com/planesailingio/gannet/releases/download/v0.6.5/gannet-v0.6.5-x86_64-unknown-linux-musl.tar.gz"
      sha256 "640eb24338c10e684f47ef96e8d617ba91787024ce76d28186b93f343d084f58"
    end
  end

  def install
    bin.install "gannet"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gannet --version")
  end
end
