# typed: false
# frozen_string_literal: true

# This file is generated by scripts/update-tap.sh in planesailingio/hats. DO NOT EDIT.
class Hats < Formula
  desc "One laptop, many hats: dotfiles and per-shell client contexts"
  homepage "https://github.com/planesailingio/hats"
  version "0.8.0"
  license "MIT"

  # The age plugin that unseals the credential envelope. hats drives it as a
  # subprocess, and the age crate resolves it on PATH at call time, so it has to
  # be present rather than merely suggested.
  #
  # On Linux it also needs a running pcscd to reach the smartcard; that is a
  # system service Homebrew does not manage, and `hats doctor` says so.
  depends_on "age-plugin-yubikey"

  # git is the only other hard requirement, and every machine with a dotfiles
  # repo already has it. fzf and kubectl are optional and reported by
  # `hats doctor`.

  on_macos do
    on_intel do
      url "https://github.com/planesailingio/hats/releases/download/v0.8.0/hats_0.8.0_x86_64-apple-darwin.tar.gz"
      sha256 "1615151b5c38cb6e0a5af81a40b20896869002d344cfef1ea9f5435cd1878e47"
    end
    on_arm do
      url "https://github.com/planesailingio/hats/releases/download/v0.8.0/hats_0.8.0_aarch64-apple-darwin.tar.gz"
      sha256 "98f1a4d06d0f8ca62c7c31d7b611a9c1545cd84c692b849c6a31c62953463d8e"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planesailingio/hats/releases/download/v0.8.0/hats_0.8.0_x86_64-unknown-linux-gnu.tar.gz"
        sha256 "23bb13893c451131f9f09ea0133174e8ce2fc6ced9ca90399107b0bfcda3e964"
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planesailingio/hats/releases/download/v0.8.0/hats_0.8.0_aarch64-unknown-linux-gnu.tar.gz"
        sha256 "42a20c1aea83107e8290507cd7e3b2864a753600e83ebbd2c7d6e4b7c4cf131a"
      end
    end
  end

  def install
    bin.install "bin/hats"
    bash_completion.install "completions/hats.bash" => "hats"
    zsh_completion.install "completions/_hats"
    fish_completion.install "completions/hats.fish"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hats --version")
    # doctor exits non-zero in the sandbox because no repo is cloned there, but
    # the report must still name the git check, which proves it ran.
    assert_match "git", shell_output("#{bin}/hats doctor 2>&1 || true")
  end
end
