# typed: false
# frozen_string_literal: true

# This file is generated by scripts/update-tap.sh in planesailingio/hats. DO NOT EDIT.
class Hats < Formula
  desc "One laptop, many hats: dotfiles and per-shell client contexts"
  homepage "https://github.com/planesailingio/hats"
  version "0.3.0"
  license "MIT"

  # The age plugin that unseals the credential envelope. hats drives it as a
  # subprocess, and the age crate resolves it on PATH at call time, so it has to
  # be present rather than merely suggested.
  #
  # On Linux it also needs a running pcscd to reach the smartcard; that is a
  # system service Homebrew does not manage, and `hats doctor` says so.
  depends_on "age-plugin-yubikey"

  # git is the only other hard requirement, and every machine with a dotfiles
  # repo already has it. fzf and kubectl are optional and reported by
  # `hats doctor`.

  on_macos do
    on_intel do
      url "https://github.com/planesailingio/hats/releases/download/v0.3.0/hats_0.3.0_x86_64-apple-darwin.tar.gz"
      sha256 "244f1586c0232fd5a21e43f6d3176084b91d903c2d2cbc52c680866704755f78"
    end
    on_arm do
      url "https://github.com/planesailingio/hats/releases/download/v0.3.0/hats_0.3.0_aarch64-apple-darwin.tar.gz"
      sha256 "df708a9f62c5e2dce3dffe3bed0f22d5b31e684f8f73a13444d662b2fdfa9b63"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planesailingio/hats/releases/download/v0.3.0/hats_0.3.0_x86_64-unknown-linux-gnu.tar.gz"
        sha256 "dbc85d15d6c3770a69dd47c32da3035b0cae7793910793bec895ae13f93e2ac7"
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planesailingio/hats/releases/download/v0.3.0/hats_0.3.0_aarch64-unknown-linux-gnu.tar.gz"
        sha256 "db411cff62d55c096ca2d091a748ec464b3b8373fd817421219ae636f27ec8f2"
      end
    end
  end

  def install
    bin.install "bin/hats"
    bash_completion.install "completions/hats.bash" => "hats"
    zsh_completion.install "completions/_hats"
    fish_completion.install "completions/hats.fish"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hats --version")
    # doctor exits non-zero in the sandbox because no repo is cloned there, but
    # the report must still name the git check, which proves it ran.
    assert_match "git", shell_output("#{bin}/hats doctor 2>&1 || true")
  end
end
