# typed: false
# frozen_string_literal: true

# This file is generated by scripts/update-tap.sh in planesailingio/hats. DO NOT EDIT.
class Hats < Formula
  desc "One laptop, many hats: dotfiles and per-shell client contexts"
  homepage "https://github.com/planesailingio/hats"
  version "0.5.0"
  license "MIT"

  # The age plugin that unseals the credential envelope. hats drives it as a
  # subprocess, and the age crate resolves it on PATH at call time, so it has to
  # be present rather than merely suggested.
  #
  # On Linux it also needs a running pcscd to reach the smartcard; that is a
  # system service Homebrew does not manage, and `hats doctor` says so.
  depends_on "age-plugin-yubikey"

  # git is the only other hard requirement, and every machine with a dotfiles
  # repo already has it. fzf and kubectl are optional and reported by
  # `hats doctor`.

  on_macos do
    on_intel do
      url "https://github.com/planesailingio/hats/releases/download/v0.5.0/hats_0.5.0_x86_64-apple-darwin.tar.gz"
      sha256 "77fa3d039e600ffae7fc349d9ddbd09b1cf8aefc06885a0a0179c550c8d684cc"
    end
    on_arm do
      url "https://github.com/planesailingio/hats/releases/download/v0.5.0/hats_0.5.0_aarch64-apple-darwin.tar.gz"
      sha256 "9b08f4f91e6abd8f51b55578aefa16c2997bce236a6c9d635b599674392e613a"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planesailingio/hats/releases/download/v0.5.0/hats_0.5.0_x86_64-unknown-linux-gnu.tar.gz"
        sha256 "00832e2d3645a71aead889d8d58535e18f891d9efa2dd302a6ab3e514202e656"
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planesailingio/hats/releases/download/v0.5.0/hats_0.5.0_aarch64-unknown-linux-gnu.tar.gz"
        sha256 "d9e29920f40515459fc802bd285c90d5b74e86eb6ae80e164f377e0105cea585"
      end
    end
  end

  def install
    bin.install "bin/hats"
    bash_completion.install "completions/hats.bash" => "hats"
    zsh_completion.install "completions/_hats"
    fish_completion.install "completions/hats.fish"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hats --version")
    # doctor exits non-zero in the sandbox because no repo is cloned there, but
    # the report must still name the git check, which proves it ran.
    assert_match "git", shell_output("#{bin}/hats doctor 2>&1 || true")
  end
end
