# typed: false
# frozen_string_literal: true

# This file is generated by scripts/update-tap.sh in planesailingio/moss. DO NOT EDIT.
class Moss < Formula
  desc "Cross-platform user-profile backup and restore on top of Kopia"
  homepage "https://github.com/planesailingio/moss"
  version "0.7.1"
  license "MIT"

  # Kopia is the backup engine; moss shells out to it (spec §45).
  depends_on "kopia"

  on_macos do
    on_intel do
      url "https://github.com/planesailingio/moss/releases/download/v0.7.1/moss_0.7.1_x86_64-apple-darwin.tar.gz"
      sha256 "000dbfbccbb4455d5c9bea085b63e51987c9c83ed0a3487511adca5fcaea4c88"
    end
    on_arm do
      url "https://github.com/planesailingio/moss/releases/download/v0.7.1/moss_0.7.1_aarch64-apple-darwin.tar.gz"
      sha256 "0671d75def6d1199773bb2e9887cb799f75cf438591a844246e3bb955afd0fac"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planesailingio/moss/releases/download/v0.7.1/moss_0.7.1_x86_64-unknown-linux-gnu.tar.gz"
        sha256 "7769a56a4cb1c6b097f161865ecceb61d93ae38c94dadb0d5b710b903890d43f"
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planesailingio/moss/releases/download/v0.7.1/moss_0.7.1_aarch64-unknown-linux-gnu.tar.gz"
        sha256 "7db6891b1a6e8d7cb381b47c855f341defbec3eaf6de71c7faa4b7729a44c03f"
      end
    end
  end

  def install
    bin.install "bin/moss"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/moss --version")
    # No repository is configured inside the test sandbox, so doctor may exit
    # non-zero; the report must still contain the Kopia check, which proves
    # the dependency is wired up.
    assert_match "kopia", shell_output("#{bin}/moss doctor --json 2>&1 || true")
  end
end
