# typed: false
# frozen_string_literal: true

# This file is generated by scripts/update-tap.sh in planesailingio/moss. DO NOT EDIT.
class Moss < Formula
  desc "Cross-platform user-profile backup and restore on top of Kopia"
  homepage "https://github.com/planesailingio/moss"
  version "0.7.2"
  license "MIT"

  # Kopia is the backup engine; moss shells out to it (spec §45).
  depends_on "kopia"

  on_macos do
    on_intel do
      url "https://github.com/planesailingio/moss/releases/download/v0.7.2/moss_0.7.2_x86_64-apple-darwin.tar.gz"
      sha256 "410428c641d367b7d2c379c8f6e88a3b715552bddfb950ff279df5c98396a4e2"
    end
    on_arm do
      url "https://github.com/planesailingio/moss/releases/download/v0.7.2/moss_0.7.2_aarch64-apple-darwin.tar.gz"
      sha256 "427feaa2da09ebd43796c2037f9dc33d7b6caba4ab51eaea0d3a65ffdb1a4c48"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planesailingio/moss/releases/download/v0.7.2/moss_0.7.2_x86_64-unknown-linux-gnu.tar.gz"
        sha256 "c2671314c77c5c3f7bda69f738ef314cb977eb5f9f81e93bfe253fe42a35d615"
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planesailingio/moss/releases/download/v0.7.2/moss_0.7.2_aarch64-unknown-linux-gnu.tar.gz"
        sha256 "e9ae5ec561fc5fc23dbb559dc73e3730b6b1dd7c9cc35ae923f28c8dcaa618f1"
      end
    end
  end

  def install
    bin.install "bin/moss"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/moss --version")
    # No repository is configured inside the test sandbox, so doctor may exit
    # non-zero; the report must still contain the Kopia check, which proves
    # the dependency is wired up.
    assert_match "kopia", shell_output("#{bin}/moss doctor --json 2>&1 || true")
  end
end
