# typed: false
# frozen_string_literal: true

# This file is generated by scripts/update-tap.sh. DO NOT EDIT.
class Twig < Formula
  desc "Opinionated Git repository bootstrapper with Grove worktrees"
  homepage "https://github.com/planesailingio/twig"
  version "0.8.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/planesailingio/twig/releases/download/v0.8.4/twig_0.8.4_x86_64-apple-darwin.tar.gz"
      sha256 "d5ce9fd72a7d9e6379d611330d74ffd1dc7a08305fd41254164b552a25f700e6"

      def install
        bin.install "bin/twig"
      end
    end
    on_arm do
      url "https://github.com/planesailingio/twig/releases/download/v0.8.4/twig_0.8.4_aarch64-apple-darwin.tar.gz"
      sha256 "14cdcc9970f58fd4b8afaf246ea68e79e01cc17cc18f294be8bb4f6c015f10d8"

      def install
        bin.install "bin/twig"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planesailingio/twig/releases/download/v0.8.4/twig_0.8.4_x86_64-unknown-linux-gnu.tar.gz"
        sha256 "222262c0aead89960e415db7b30b1438891a627b8abbe004293bb7860ed48b30"

        def install
          bin.install "bin/twig"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planesailingio/twig/releases/download/v0.8.4/twig_0.8.4_aarch64-unknown-linux-gnu.tar.gz"
        sha256 "3b6316d2044e1b79a15f894a2b2e3ddc834af62f3b0c8dbb4b3b20ca9e34a732"

        def install
          bin.install "bin/twig"
        end
      end
    end
  end

  test do
    assert_match "twig", shell_output("#{bin}/twig version")
  end
end
